import Link from "next/link";
import Navbar from "../../components/Navbar";

const sections = [
  ["1. Information we may collect", `Depending on how you use RADR, we may collect account information such as name, email, account identifiers, authentication information, account type, age or date-of-birth information where collected, guardian relationships and preferences. Athlete profile information may include name, photo, biography, sport, position, gender, age group, general location, school or college, languages, eligible countries, sporting history, teams, competitions, achievements, statistics, measurements, development information, height, weight, dominant side, highlights and video links. We may also collect team information, social and Platform activity, searches, follows, Watchlist activity, Feed interactions, invitations, reports, future messages, technical information, security logs and, when introduced, subscription and transaction information.`],
  ["2. How we collect information", `We may collect information directly from you; from a parent or guardian; from an athlete whose profile you manage; from team administrators or other users interacting with you; through use of RADR and team invitations; from third-party services you choose to connect; through analytics and technical systems; from public sources where lawful and appropriate; and from service providers acting on our behalf.`],
  ["3. Junior athletes", `RADR may contain profiles relating to children and young people where permitted by law. Where a profile is managed by a parent or guardian, RADR may record that relationship and identify the profile as Parent Managed, Guardian Managed or similar. Parents and guardians should carefully consider what information they provide. A name, photograph, school, team, age group, sporting schedule and location can collectively make an athlete identifiable. RADR may introduce additional privacy defaults, age-assurance, guardian controls or restrictions as law and the Platform evolve.`],
  ["4. Why we use personal information", `We may use personal information where permitted by law to create and maintain accounts and athlete profiles; operate teams, invitations, discovery, search, Follow, Watchlist and Feed; provide achievements, highlights, athlete-development and RADR Resumé features; personalise RADR; provide support; administer subscriptions; prevent fraud and misuse; investigate inaccurate profiles; moderate content; protect users; maintain security; enforce our Terms; diagnose technical problems; analyse performance and engagement; improve and develop products; conduct research and analytics; support RADR's commercial development; comply with law; and protect legitimate legal interests.`],
  ["5. Public information", `Some RADR functionality is intended to make athlete information publicly discoverable. Information configured as public may be accessible outside an athlete's immediate network and may, depending on Platform configuration, be accessible without logging in. Public information may be viewed, shared, copied, screenshotted, indexed or linked by third parties. RADR may not be able to control or delete copies independently made outside RADR.`],
  ["6. Platform data and analytics", `RADR may analyse Platform information to understand usage, discovery, team engagement, growth, feature performance, safety risks, fraud, technical performance and opportunities for new products or services. Where practicable, RADR may aggregate or de-identify information. RADR may use and commercialise aggregated or de-identified information for analytics, research, business intelligence, product development and commercial partnerships where permitted by law. RADR does not claim an unrestricted right to use identifiable personal information for any purpose whatsoever.`],
  ["7. Changes to how information appears", `As RADR develops, information already provided may move to another section, be presented differently, combined with related information, summarised, used in new functionality, become subject to new visibility controls, cease to be publicly displayed, be archived or otherwise reorganised. RADR may make these changes at its discretion where consistent with applicable law and this Policy. Stored information is not guaranteed to remain displayed in the same location or format.`],
  ["8. Disclosure of information", `We may disclose personal information where reasonably necessary to service providers supporting RADR, including hosting, database, authentication, analytics, communications, security and payment providers; professional advisers and contractors; law-enforcement or regulators where required or authorised by law; potential purchasers, investors or transaction advisers in a genuine corporate transaction; and other parties where you authorise disclosure. Public profile information is disclosed according to Platform functionality and applicable privacy settings.`],
  ["9. Sale, merger or restructuring", `If RADR or its business or assets are sold, merged, financed, reorganised or transferred, information held by RADR may form part of that transaction, subject to applicable privacy law.`],
  ["10. Overseas processing", `RADR may use technology providers that store or process information outside Australia. Where applicable, RADR will take reasonable steps required by Australian privacy law in relation to overseas disclosures. Relevant countries may change as providers change and this Policy may be updated where additional disclosure is required.`],
  ["11. Storage and security", `RADR takes reasonable technical and organisational measures designed to protect personal information against misuse, interference, loss and unauthorised access, modification or disclosure. Measures may include authentication, database controls, access restrictions, infrastructure encryption, monitoring, backups and security logging. No online system can guarantee absolute security.`],
  ["12. Data retention", `RADR may retain information for as long as reasonably required to provide the Platform, maintain account history, comply with law, resolve disputes, prevent fraud, maintain security, enforce agreements, maintain backups and support legitimate business requirements. Information may be deleted, anonymised or de-identified when no longer reasonably required, subject to applicable law.`],
  ["13. Account deletion", `Users may request account closure. A parent or guardian may request closure or deletion of a managed athlete profile subject to appropriate authority checks. Deletion may not immediately remove information from backups, security or fraud-prevention records, legal records, or copies independently made by third parties while information was public. RADR may retain information where required or permitted by law.`],
  ["14. Access and correction", `You may request access to personal information RADR holds about you and correction of inaccurate information. Parents or guardians may make appropriate requests for a junior athlete profile where they have authority. RADR may verify identity or authority before responding. Some information can be updated directly through RADR.`],
  ["15. Accuracy", `Users should keep information accurate and current. RADR may investigate information that appears false, misleading, fraudulent or materially inaccurate, request supporting evidence, and restrict or remove information while an investigation occurs.`],
  ["16. Cookies and similar technologies", `RADR may use cookies, local storage, analytics and similar technologies to keep users signed in, remember preferences, maintain functionality, measure usage, understand performance, diagnose errors, protect security and improve RADR. Additional controls may be introduced as the Platform develops or where required by law.`],
  ["17. Communications and marketing", `RADR may send service communications necessary to operate an account. Where permitted by law, RADR may also send information about updates, features, sporting opportunities, Premium services, promotions and related RADR products or services. Appropriate opt-out methods will be provided for marketing where required. Essential account, security and transactional communications may still be sent.`],
  ["18. Future messaging", `If RADR introduces messaging, comments or other communications, information associated with those communications may be processed to deliver messages, maintain communication history, provide safety functionality, investigate reports, detect abuse, prevent fraud, enforce RADR rules and comply with law. RADR may introduce special communication controls for junior athletes.`],
  ["19. Automated systems and recommendations", `RADR may use automated systems to organise, rank, recommend or display athletes, teams, content or opportunities. Relevant signals may include sport, location, profile completeness, relationships, follows, Watchlist status, team membership, activity or other Platform signals. These systems may change. Ranking or recommendation does not constitute endorsement.`],
  ["20. Premium features", `If RADR introduces Premium services, we may process subscription type and status, billing period, transactions, Premium feature usage and subscription preferences. Payment providers may independently process payment information under their own privacy policies.`],
  ["21. Children and regulatory change", `Online privacy and safety regulation relating to children is evolving. RADR may modify eligibility, age requirements, parental controls, privacy settings, public-profile functionality, communications or other features where necessary to comply with law or improve athlete safety. Changes may affect existing accounts or displayed information.`],
  ["22. Data breaches", `If RADR experiences an eligible data breach, RADR will take steps required under applicable privacy and data-breach notification laws and may contact affected users, parents or guardians, regulators or other relevant parties where required or appropriate.`],
  ["23. Privacy complaints", `If you have a privacy concern, contact RADR using the details below. We will consider the complaint and respond within a reasonable period. Where applicable, individuals may also have the right to complain to the Office of the Australian Information Commissioner.`],
  ["24. Changes to this Policy", `RADR may update this Privacy Policy as the Platform, business, technology or applicable law changes. The current version will state its latest update date. Where appropriate, RADR may provide additional notice of material changes.`],
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#0B1F5C] text-white">
      <Navbar />
      <section className="mx-auto max-w-4xl px-4 py-10 sm:px-6 md:py-16">
        <div className="rounded-3xl border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur md:p-10">
          <p className="text-xs font-bold uppercase tracking-[0.22em] text-[#D8F200]">RADR Legal</p>
          <h1 className="mt-3 text-3xl font-extrabold md:text-5xl">Privacy Policy</h1>
          <p className="mt-3 text-sm text-white/50">Last updated: 21 September 2026</p>
          <p className="mt-6 leading-7 text-white/75">RADR respects the privacy of athletes, families and other people who use our Platform. This Policy explains how <strong>[RADR LEGAL ENTITY] ABN [ABN]</strong> (“RADR”, “we”, “us” or “our”) collects, holds, uses and discloses personal information. We are particularly conscious that RADR may contain information relating to junior athletes.</p>
          <div className="mt-8 space-y-7">
            {sections.map(([title, body]) => (
              <section key={title}>
                <h2 className="text-lg font-bold text-white md:text-xl">{title}</h2>
                <p className="mt-2 leading-7 text-white/70">{body}</p>
              </section>
            ))}
            <section>
              <h2 className="text-lg font-bold md:text-xl">25. Contact</h2>
              <p className="mt-2 leading-7 text-white/70">Privacy enquiries, access or correction requests and complaints can be directed to <strong>[CONTACT EMAIL]</strong>. Legal entity: <strong>[RADR LEGAL ENTITY]</strong>, ABN <strong>[ABN]</strong>, address <strong>[ADDRESS]</strong>.</p>
            </section>
          </div>
          <div className="mt-10 flex flex-wrap gap-3 border-t border-white/10 pt-6 text-sm">
            <Link href="/terms" className="font-semibold text-[#D8F200] hover:underline">Terms of Use</Link>
            <span className="text-white/25">•</span>
            <Link href="/" className="text-white/60 hover:text-white">Back to RADR</Link>
          </div>
        </div>
      </section>
    </main>
  );
}
