import Link from "next/link";
import Navbar from "../../components/Navbar";

const sections = [
  ["1. What RADR is", `RADR is an athlete profile, development, team, discovery and networking platform. Features may include athlete profiles, sporting experience, teams, achievements, highlights, athlete development information, discovery, Follow, Watchlist, Feed, team invitations, guardian-managed profiles, RADR Resumé, communications, training or development programs, and free or paid services. Features may change over time.`],
  ["2. Accounts and eligibility", `You must provide accurate information and must not create a false identity, impersonate another person, deliberately misrepresent age, sporting history, achievements, qualifications or team membership, create a profile without appropriate authority, or access another person's account without permission. RADR may introduce age, identity, guardian or eligibility checks and may restrict features based on age, location, account type, safety or legal requirements.`],
  ["3. Junior athletes and managed profiles", `Where permitted by law, a child or young person's athlete profile may be created or managed by an authorised parent, legal guardian or other person with appropriate authority. That person confirms they have authority to manage the profile and provide its information, photos, videos and other content; will keep information accurate and appropriate; understands that information made public may be publicly visible; and will appropriately supervise use of RADR where required. RADR may identify a profile as Parent Managed or Guardian Managed. The athlete remains the primary identity represented by the profile.`],
  ["4. Public athlete information", `RADR is designed in part to make athletes discoverable. Depending on settings and available features, public information may include an athlete's name, preferred name, photo, sport, position, age group, gender, general location, school or college, teams, competitions, achievements, highlights, biography, development information, measurements, eligible countries, languages and other information intentionally submitted for display. Public information may be viewed, copied, shared, indexed, photographed or screenshotted by others outside RADR's control.`],
  ["5. Accuracy and profile integrity", `Users are responsible for the accuracy of information they provide. Unless expressly stated otherwise, RADR does not independently verify every achievement, statistic, measurement, team membership, competition, qualification, video or sporting claim. RADR may request evidence and may introduce verified or unverified classifications.`],
  ["6. Teams and memberships", `RADR may allow users to create, manage, join and invite people to teams. Creating a team does not by itself establish that a user is an official representative of a club, school, association or governing body. Team administrators must only exercise permissions they are authorised to exercise. A team membership displayed on RADR does not itself constitute official sporting registration.`],
  ["7. User Content", `User Content includes information, text, photographs, profile images, videos, links, achievements, statistics, comments, messages and other material submitted to RADR. You retain rights you hold in your User Content. By submitting it, you grant RADR a worldwide, non-exclusive, royalty-free licence to host, store, reproduce, process, format, adapt and display that content as reasonably required to operate, administer, secure, moderate, promote, improve and develop RADR and related services, subject to applicable law. You must have the rights and permissions necessary to submit the content.`],
  ["8. Acceptable conduct", `You must not use RADR to publish, send or distribute threatening, abusive, bullying, harassing, hateful, discriminatory, sexually inappropriate, exploitative, deliberately humiliating, defamatory, fraudulent, deceptive, unlawfully violent, privacy-invasive or otherwise unlawful content. You must not groom, exploit or inappropriately contact a child, distribute spam or harmful code, or intimidate, pressure or exploit athletes.`],
  ["9. Messaging and communications", `RADR may introduce messaging, comments or other user-to-user communications. These will be subject to these Terms and any additional safety rules. RADR may impose special restrictions on communications involving junior athletes, including restrictions based on age, relationship, account type or guardian approval, and may investigate reported communications or remove communication privileges.`],
  ["10. Moderation and account action", `RADR may investigate activity reasonably suspected to breach these Terms, compromise safety, undermine Platform integrity or create legal, security or reputational risk. Subject to applicable law, RADR may request information or evidence, hide or remove content, restrict profile visibility or features, freeze or suspend an account, remove a profile, terminate an account, or prevent repeat account creation. This may occur where RADR reasonably suspects fake, misleading or materially inaccurate information, impersonation, fabricated achievements or statistics, offensive content, harassment, misuse of personal information, fraud, safety concerns or other breaches. RADR is not required to publicly disclose confidential details of an investigation or enforcement decision.`],
  ["11. Reports", `Users may report profiles, content, communications or behaviour. RADR may determine how reports are investigated and resolved. A report does not guarantee removal. Knowingly malicious or deliberately false reporting may itself be misuse of RADR.`],
  ["12. Use of information and Platform data", `RADR may collect and use information in accordance with its Privacy Policy and applicable law to operate and secure the Platform; display athlete and team information; provide discovery, Feed, Follow and Watchlist functionality; personalise experiences; administer teams; analyse engagement; improve and develop products; moderate misuse; communicate with users; support commercial development; and generate aggregated or de-identified insights. RADR may commercially use aggregated or de-identified information where permitted by law.`],
  ["13. Changes to RADR and information display", `RADR is an evolving product. RADR may change page layouts, profile formats, categories, labels, search, ranking, feeds, recommendations, privacy controls, account types, data fields, visibility and feature availability. Information previously visible may later be reorganised, summarised, archived, restricted, hidden or displayed differently. RADR does not guarantee that information will always be presented in the same manner in which it was originally entered.`],
  ["14. Platform availability and discontinuation", `RADR does not guarantee uninterrupted or error-free operation. RADR may add, remove, restrict, suspend or discontinue any part of the Platform and may discontinue RADR entirely for commercial, operational, legal, technical, safety or other reasons. Subject to applicable law and contractual obligations, RADR is not required to publicly disclose confidential commercial, technical or operational reasons for doing so. Where reasonably practicable, RADR may provide notice of material discontinuation.`],
  ["15. Third-party services", `RADR may rely on third-party hosting, authentication, database, video, analytics, payment, communications and other providers. RADR is not responsible for the independent operation, content, privacy practices or availability of third-party services. External links do not necessarily constitute endorsement.`],
  ["16. Athlete discovery and recruitment", `RADR may facilitate discovery by athletes, teams, coaches, recruiters, sporting organisations and other users. RADR does not guarantee selection, recruitment, scholarships, contracts, trials, team placement, employment, representation or sporting opportunities. Users remain responsible for appropriate checks before engaging with another person or organisation.`],
  ["17. RADR Resumé and generated material", `RADR may provide résumé, profile, development, analysis or other generated features. Generated material is a tool to assist users and may require review or correction. Users remain responsible for checking information they submit or distribute.`],
  ["18. Free and Premium services", `RADR may offer free, Premium or other paid tiers. Features and pricing may differ and may change. Before purchase, RADR will disclose applicable pricing, billing frequency and material subscription conditions. Where recurring billing is offered, renewal and cancellation arrangements will be disclosed at purchase. Unless otherwise stated, cancellation ordinarily prevents further renewal while access continues until the end of an already-paid billing period. Refund and consumer rights required by law continue to apply. Trials, discounts and promotions may have additional disclosed terms. A feature being free at one time does not guarantee it will remain free indefinitely.`],
  ["19. Payments", `Paid services may use third-party payment providers. RADR may not directly store complete payment-card details. Users must ensure payment information is current and authorised. Additional payment terms may apply at checkout.`],
  ["20. Intellectual property", `Except for User Content and third-party material, RADR's software, design, interfaces, branding, graphics, logos, databases and other Platform materials are owned by or licensed to RADR. You must not unlawfully copy, reverse engineer, reproduce or commercially exploit them.`],
  ["21. Security", `Users are responsible for protecting account credentials and should notify RADR if an account may be compromised. RADR may reset credentials, restrict access or take other protective action where security is in question.`],
  ["22. Privacy", `Use of RADR is also governed by the RADR Privacy Policy. Users should read it before providing personal information.`],
  ["23. Disclaimer", `RADR provides a technology platform. Unless expressly stated otherwise, RADR does not independently endorse, certify or verify athletes, coaches, teams, recruiters or sporting organisations. RADR information is not medical, legal, financial or professional sporting advice.`],
  ["24. Liability", `To the maximum extent permitted by law, RADR is not liable for loss arising solely from inaccurate User Content, interactions between users, missed sporting opportunities, third-party conduct or service interruptions, unauthorised copying of information deliberately made public, or changes to free Platform functionality. Nothing in these Terms excludes, restricts or modifies rights or remedies that cannot lawfully be excluded, including applicable Australian Consumer Law rights.`],
  ["25. Responsibility for breaches", `To the extent permitted by law, you are responsible for loss reasonably suffered by RADR arising from your unlawful conduct, deliberate breach of these Terms, infringement of another person's rights, or content you were not authorised to provide. This does not make you responsible for RADR's own unlawful conduct or liability that cannot lawfully be excluded.`],
  ["26. Closing accounts", `Users may request account closure through functionality provided by RADR or by contacting RADR. Closure may not require immediate deletion of every record. RADR may retain information where reasonably necessary for legal compliance, security, fraud prevention, dispute resolution, backups or other lawful purposes.`],
  ["27. Changes to these Terms", `RADR may update these Terms as the Platform, business or law changes. The current version will state its latest revision date. Where a change materially affects users' rights or an existing paid service, RADR will take reasonable steps to provide appropriate notice where required.`],
  ["28. Governing law", `These Terms are governed by the laws of New South Wales, Australia, subject to any rights a consumer has under applicable law.`],
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0B1F5C] text-white">
      <Navbar />
      <section className="mx-auto max-w-4xl px-4 py-10 sm:px-6 md:py-16">
        <div className="rounded-3xl border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur md:p-10">
          <p className="text-xs font-bold uppercase tracking-[0.22em] text-[#D8F200]">RADR Legal</p>
          <h1 className="mt-3 text-3xl font-extrabold md:text-5xl">Terms of Use</h1>
          <p className="mt-3 text-sm text-white/50">Last updated: 21 September 2026</p>
          <p className="mt-6 leading-7 text-white/75">These Terms govern access to and use of the RADR website, application, platform and related services. RADR is operated by <strong>[RADR LEGAL ENTITY] ABN [ABN]</strong> (“RADR”, “we”, “us” or “our”). By creating an account, creating or managing an athlete profile, accessing authenticated features or otherwise agreeing to these Terms, you agree to be bound by them. If you create or manage a profile for another person, including a child, you also agree to these Terms in relation to your management of that profile. Nothing in these Terms excludes rights that cannot lawfully be excluded.</p>
          <div className="mt-8 space-y-7">
            {sections.map(([title, body]) => (
              <section key={title}>
                <h2 className="text-lg font-bold text-white md:text-xl">{title}</h2>
                <p className="mt-2 leading-7 text-white/70">{body}</p>
              </section>
            ))}
            <section>
              <h2 className="text-lg font-bold md:text-xl">29. Contact</h2>
              <p className="mt-2 leading-7 text-white/70">Questions about these Terms can be directed to RADR at <strong>[CONTACT EMAIL]</strong>. Legal entity: <strong>[RADR LEGAL ENTITY]</strong>, ABN <strong>[ABN]</strong>, address <strong>[ADDRESS]</strong>.</p>
            </section>
          </div>
          <div className="mt-10 flex flex-wrap gap-3 border-t border-white/10 pt-6 text-sm">
            <Link href="/privacy" className="font-semibold text-[#D8F200] hover:underline">Privacy Policy</Link>
            <span className="text-white/25">•</span>
            <Link href="/" className="text-white/60 hover:text-white">Back to RADR</Link>
          </div>
        </div>
      </section>
    </main>
  );
}
